export const LOADING_START = 'ACTION_LOADING_START';
export const LOADING_END = 'ACTION_LOADING_END';

export const ALERT_ON = 'ACTION_NOTIFICATION_ON';
export const ALERT_COUNTDOWN = 'ACTION_NOTIFICATION_COUNTDOWN';
export const ALERT_OFF = 'ACTION_NOTIFICATION_OFF';

export const SET_QUOTE_ACTIVE = 'ACTION_QUOTE_ACTIVE';
export const SET_QUOTE_IS_SPECIAL_WITH_REASON = 'ACTION_QUOTE_IS_SPECIAL_WITH_REASON';
export const SET_QUOTE_BELOW_90_WARN = 'ACTION_QUOTE_BELOW_90_WARN';
export const SET_QUOTE_NOT_SPECIAL = 'ACTION_QUOTE_NOT_SPECIAL';
export const SET_QUOTE = 'ACTION_QUOTE_SET';

export const SET_BOXES = 'ACTION_SET_BOXES';
export const CLEAR_BOXES = 'ACTION_CLEAR_BOXES';

export const SET_QUOTE_RESULT = 'ACTION_QUOTE_SET_RESULT';
export const UNSET_QUOTE_RESULT = 'ACTION_QUOTE_UNSET_RESULT';

export const SET_NEW_HISTORY = 'ACTION_APP_SET_NEW_HISTORY';
export const SET_HISTORY = 'ACTION_APP_SET_HISTORY';
export const SET_HISTORY_INDEX = 'ACTION_APP_SET_HISTORY_INDEX';
export const UNSET_HISTORY = 'ACTION_APP_UNSET_HISTORY';

export const REDIRECT_TO_CONTACT = 'ACTION_REDIRECTION_CONTACT_PAGE';
export const REDIRECT_TO_PATH = 'ACTION_REDIRECT_TO_PATH';

export const SET_GLOBAL_DATA = 'ACTION_SET_GLOBAL_DATA';

export const FETCH_BOX_DATA = 'ACTION_FETCH_BOX_DATA';
export const SUBMIT_CONTACT_DATA = 'ACTION_SUBMIT_CONTACT_DATA';

export const SET_SCREENSHOT_FILE = 'ACTION_SET_SCREENSHOT_FILE';
